### PR TITLE
Romove wrong pIndexData assignment

### PR DESCRIPTION
**Pull request by jackchentwkh**
pIndexData was assigned in line#432 with correct value.

### CODE REVIEW

**Comment by PatrickvL** [comment]
Thank you!

**Comment by PatrickvL** [comment]
Does this give a discernable positive result? If so, then how?

**Comment by jackchentwkh** [comment]
Nothing obvious yet.

**Comment by jackchentwkh** [comment]
by skipping the non-FVF support check, RalliSport shows some textures on the road surface, now I finally complete the 1st race. there are still flying polygons. Don't have much time on it yet.

**Pull request merged**
