### PR TITLE
Work in progress

### PR DESCRIPTION
**Pull request by PatrickvL**
Texture conversion with a lot less patching

### CODE REVIEW

**Comment by literalmente-game** [comment]
Reporting
ff_cxbx-r

**Comment by PatrickvL** [comment]
Oh wow, thanks. I wasn't aware this branch was being monitored so closely! Sorry for all the breakage - but as the name says: it's a work in progress. Slowly but steadily it's getting to a better state though, so just be patient and bear with me, please.

**Comment by furrya** [comment]
Reported
screenshot_1

**Comment by PatrickvL** [comment]
My oh my - Am I really being monitored that much? ;)
Thanks for the heads up though, keep them coming!

**Comment by literalmente-game** [comment]
From the last changes on https://github.com/PatrickvL/Cxbx-Reloaded/tree/WIP_VertexPatching
cxbx_bnr

**Comment by PatrickvL** [comment]
@literalmente-game Thanks for the heads-up!

I hope I'm not testing everyones patience too much, with all the work I'm doing... It's taking me much longer than I previously anticipated, but on the bright side, in the end the results will be well worth it.

**Comment by literalmente-game** [comment]
Some change on https://github.com/PatrickvL/Cxbx-Reloaded/tree/WIP_VertexPatching caused a memory leak when I was testing the game "Gauntlet Dark Legacy".

Edit1: Yu-Gi-Oh - The Dawn of Destiny had a memory leak too

Edit2: using the same build:
cxbx_nm

**Comment by literalmente-game** [comment]
Reporting test-cases results:


DumpPushBufferContents:

Baku Baku (Homebrew)
Battlestar Galactica
Buffy: The Vampire Slayer
Conflict: Desert Storm (Demo)
Dolphin (Tech Demo)
Gauntlet Dark Legacy
Grabbed by the Ghoulies (Demo)
Metal Arms (Demo)
Robotech: Battlecry 
Silent Scope 1
Smashing Drive
Yu-Gi-Oh - The Dawn of Destiny

-------------------------------

pSurfaceParent XD3DRTYPE_TEXTURE:

Silent Scope 2
Tenchu 3 (Demo)

**Pull request merged**
